server:
  port: 8001

spring:
  application:
    name: general-store
  redis:
    host: 192.168.30.251
    port: 6379
    jedis:
      pool:
        max-active: 1000
        max-wait: 10000
        max-idle: 200
        min-idle: 50
        time-between-eviction-runs: 100000
    client-type: jedis
  datasource:
    url: jdbc:mysql://192.168.30.251:3306/general_store
