server:
  port: 8002

spring:
  application:
    name: general-store-redis
  redis:
    host: "***"
    port: 6379
    jedis:
      pool:
        max-active: 1000
        max-wait: 10000
        max-idle: 200
        min-idle: 50
        time-between-eviction-runs: 100000
    client-type: jedis
  datasource:
    url: "***"
eureka:
  client:
    service-url:
      defaultZone: http://localhost:8001/eureka/
